name: CI

on:
  push:
    branches: [main, "**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun --version
      - run: bun install
      - run: bun run lint
      - run: bun test
